//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalBook.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public author()
        {
            this.products = new HashSet<product>();
        }
    
        public int au_id { get; set; }
        public string au_name { get; set; }
        public int au_createdby { get; set; }
        public System.DateTime au_createddate { get; set; }
        public int au_modifiedby { get; set; }
        public System.DateTime au_modifieddate { get; set; }
        public int au_deletedby { get; set; }
        public System.DateTime au_deleteddate { get; set; }
        public int au_isdeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
    }
}
