//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalBook.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_item
    {
        public int ci_id { get; set; }
        public int ci_sessionid { get; set; }
        public int ci_productid { get; set; }
        public int ci_quantity { get; set; }
        public int ci_createdby { get; set; }
        public System.DateTime ci_createddate { get; set; }
        public int ci_modifiedby { get; set; }
        public System.DateTime ci_modifieddate { get; set; }
        public int ci_deletedby { get; set; }
        public System.DateTime ci_deleteddate { get; set; }
        public int ci_isdeleted { get; set; }
    
        public virtual product product { get; set; }
        public virtual shopping_session shopping_session { get; set; }
    }
}
