//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalBook.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_details()
        {
            this.order_items = new HashSet<order_items>();
        }
    
        public int od_id { get; set; }
        public int od_userid { get; set; }
        public decimal od_total { get; set; }
        public int od_paymentid { get; set; }
        public int od_createdby { get; set; }
        public System.DateTime od_createddate { get; set; }
        public int od_modifiedby { get; set; }
        public System.DateTime od_modifieddate { get; set; }
        public int od_deletedby { get; set; }
        public System.DateTime od_deleteddate { get; set; }
        public int od_isdeleted { get; set; }
    
        public virtual payment_details payment_details { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { get; set; }
    }
}
