//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalBook.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payment_details()
        {
            this.order_details = new HashSet<order_details>();
        }
    
        public int pd_id { get; set; }
        public int pd_orderid { get; set; }
        public decimal pd_amount { get; set; }
        public string pd_provider { get; set; }
        public string pd_status { get; set; }
        public int pd_createdby { get; set; }
        public System.DateTime pd_createddate { get; set; }
        public int pd_modifiedby { get; set; }
        public System.DateTime pd_modifieddate { get; set; }
        public int pd_deletedby { get; set; }
        public System.DateTime pd_deleteddate { get; set; }
        public int pd_isdeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
    }
}
