//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalBook.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_maincategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product_maincategory()
        {
            this.product_category = new HashSet<product_category>();
            this.productcategory_image = new HashSet<productcategory_image>();
        }
    
        public int mpc_id { get; set; }
        public string mpc_name { get; set; }
        public string mpc_desc { get; set; }
        public int mpc_createdby { get; set; }
        public System.DateTime mpc_createddate { get; set; }
        public int mpc_modifiedby { get; set; }
        public System.DateTime mpc_modifieddate { get; set; }
        public int mpc_deletedby { get; set; }
        public System.DateTime mpc_deleteddate { get; set; }
        public int mpc_isdeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_category> product_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productcategory_image> productcategory_image { get; set; }
    }
}
