//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalBook.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.cart_item = new HashSet<cart_item>();
            this.order_items = new HashSet<order_items>();
        }
    
        public int p_id { get; set; }
        public string p_name { get; set; }
        public string p_desc { get; set; }
        public decimal p_price { get; set; }
        public int p_year { get; set; }
        public string p_edition { get; set; }
        public string p_isbn { get; set; }
        public int category_id { get; set; }
        public int inventory_id { get; set; }
        public int discount_id { get; set; }
        public int author_id { get; set; }
        public int publisher_id { get; set; }
        public int p_createdby { get; set; }
        public System.DateTime p_createddate { get; set; }
        public int p_modifiedby { get; set; }
        public System.DateTime p_modifieddate { get; set; }
        public int p_deletedby { get; set; }
        public System.DateTime p_deleteddate { get; set; }
        public int p_isdeleted { get; set; }
    
        public virtual author author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart_item> cart_item { get; set; }
        public virtual discount discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { get; set; }
        public virtual product_category product_category { get; set; }
        public virtual product_inventory product_inventory { get; set; }
        public virtual publisher publisher { get; set; }
    }
}
