//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalBook.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class publisher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public publisher()
        {
            this.products = new HashSet<product>();
        }
    
        public int pub_id { get; set; }
        public string pub_name { get; set; }
        public int pub_createdby { get; set; }
        public System.DateTime pub_createddate { get; set; }
        public int pub_modifiedby { get; set; }
        public System.DateTime pub_modifieddate { get; set; }
        public int pub_deletedby { get; set; }
        public System.DateTime pub_deleteddate { get; set; }
        public int pub_isdeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
    }
}
