//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalBook.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopping_session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shopping_session()
        {
            this.cart_item = new HashSet<cart_item>();
        }
    
        public int ss_id { get; set; }
        public int ss_userid { get; set; }
        public decimal ss_total { get; set; }
        public int ss_createdby { get; set; }
        public System.DateTime ss_createddate { get; set; }
        public int ss_modifiedby { get; set; }
        public System.DateTime ss_modifieddate { get; set; }
        public int ss_deletedby { get; set; }
        public System.DateTime ss_deleteddate { get; set; }
        public int ss_isdeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart_item> cart_item { get; set; }
        public virtual user user { get; set; }
    }
}
