//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalBook.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu_1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubMenu_1()
        {
            this.SubMenu_2 = new HashSet<SubMenu_2>();
        }
    
        public int sm1_id { get; set; }
        public int sm1_menuid { get; set; }
        public string sm1_name { get; set; }
        public string sm1_desc { get; set; }
        public string sm1_url { get; set; }
        public int sm1_level { get; set; }
    
        public virtual Menu Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubMenu_2> SubMenu_2 { get; set; }
    }
}
